name: Vulnerable

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        run: ${{ github.event.issue.body }}
